# Generated by Django 5.2 on 2025-05-24 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('gaming', 'Игровой'), ('office', 'Офисный'), ('workstation', 'Рабочая станция'), ('home', 'Домашний мультимедиа')], default='gaming', max_length=20)),
                ('priority', models.CharField(choices=[('balanced', 'Балансированная сборка'), ('cpu', 'Процессор'), ('gpu', 'Видеокарта'), ('storage', 'Память и накопители')], default='balanced', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hello_preferences', related_query_name='hello_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hello_userpreferences',
            },
        ),
    ]
